### ISSUE TITLE
No code hinting after a variable/method is defined

### ISSUE THREAD

**Issue by henrhuang** [xjsender/haoide-vscode#11]
After a variable/method is defined, there is no code hinting when we try to type the variable/method, we have to go back to the place where the variable/method we define before if we forget the variable/method name.

**Comment by xjsender** [comment]
@henrhuang , recommend you to install [All Autocomplete
](https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete)

**Comment by xjsender** [comment]
I will add recommendations for haoide when you install haoide at the first time.
