### ISSUE TITLE
Nice to display the select option list when we use picklist type field for operation

### ISSUE THREAD

**Issue by ViciaWang** [xjsender/haoide-vscode#13]
Dear,
it's nice for us to display all select options when we operate on picklist field.

**Comment by xjsender** [comment]
Already delivered.

![image](https://user-images.githubusercontent.com/1450977/67502309-43989800-f6b8-11e9-8bb4-f5afb4679c8d.png)

**Comment by xjsender** [comment]
Already Delivered

![image](https://user-images.githubusercontent.com/1450977/67502728-f79a2300-f6b8-11e9-9377-d0171601a645.png)
