### ISSUE TITLE
Wrong Metadata definition for Visualforce Page

### ISSUE THREAD

**Issue by naveenila1221** [xjsender/haoide-vscode#14]
Hi, 

 

I tried creating an visualforce page using the Option 
HaoIde: Create New Visulaforce Page

The page created and sits in the src/pages folder of my project. 
However I am unable to save the back to the server. 

When I opened the metadata xml of the page. It is showing "**ApexTrigger**" instead of **ApexPage**. Below you can find the sample of it. 

```
<?xml version="1.0" encoding="UTF-8"?>
<ApexTrigger xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>46.0</apiVersion>
    <label>TestDevForumQues</label>
</ApexTrigger>
```
**NOTE:** I do proposed file changes can you review and accept the same.

**Comment by xjsender** [comment]
@naveenila1221 Thanks, already merged your pull request.
