### ISSUE TITLE
No indication of errors when using Save this file to server

### ISSUE THREAD

**Issue by Orion8112** [xjsender/haoide-vscode#18]
I have noticed that when using the "Save This File To Server" command that there is no indication that an error has occurred and that the file was not saved. As opposed to the "Deploy This File To Server" command which displays errors. Is there any way that Save behavior can be altered to indicate a problem saving?

![image](https://user-images.githubusercontent.com/53923721/68352472-7cc01600-0156-11ea-9376-bb573751fe9e.png)

**Comment by xjsender** [comment]
@naveenila1221 I push wrong code to repo, I will remove this from next release.
