### ISSUE TITLE
Unable to open 'file:///xxxController.js ⟷ file:///': Unable to read file (Error: Expected file \ is actually a directory).

### ISSUE THREAD

**Issue by Xshaoyi** [xjsender/haoide-vscode#22]
Get this error message when click diff this file with Server:
Step to reproduce:
1.go to controller.js of a lightning component
2.click the command 'diff this file with Server'

Looks like this **diff** function has some issue in lightning component

**Comment by lushang** [comment]
After I fixed the deployment aura component Controller.js and Helper.js to server issue. I cannot reproduce the issue. Please check this issue in the new version of haoIDE

**Comment by Xshaoyi** [comment]
Thanks!
