### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Orion8112** [xjsender/haoide-vscode#3]
It would be a good idea for you to update the README file with step by step instructions on how to install vscode and haoide-vscode. Its not a good idea to assume that all Salesforce Dev's will  know how to do this.

**Comment by xjsender** [comment]
@Orion8112 , I will release a vsix package for installing and also update readme for how to contribute in the next week.

**Comment by xjsender** [comment]
Please check the release [v0.0.1](https://github.com/xjsender/haoide-vscode/releases/tag/v0.0.1), you just need to follow the [manual instruction](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) in the vscode.

**Comment by xjsender** [comment]
@Orion8112 you can install by searching ``haoide-vscode`` in the marketplace

**Comment by naveenila1221** [comment]
What is the base version of visual studio this extension supports. 

I am getting below error: 

Unable to install Extension 'mouseliu.haoide-vscode-0.1.4' as it is not compatible with Code '1.26.1'.

**Comment by xjsender** [comment]
latest version, currently, it is 1.35.0
