### ISSUE TITLE
Unable to install because, the extension 'mouseliu.haoide-vscode' compatible with current version '1.31.1' of VS Code is not found.

### ISSUE THREAD

**Issue by naveenila1221** [xjsender/haoide-vscode#7]
I am getting below error while trying to install haoide-vscode : 

Unable to install because, the extension 'mouseliu.haoide-vscode' compatible with current version '1.31.1' of VS Code is not found.

**Comment by xjsender** [comment]
latest version, currently, it is 1.35.0
